// Code generated by protoc-gen-go. DO NOT EDIT.
// source: UserService.proto

package UserService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TileInfo struct {
	TvEmac               string               `protobuf:"bytes,1,opt,name=tvEmac,proto3" json:"tvEmac,omitempty"`
	TileId               string               `protobuf:"bytes,2,opt,name=tileId,proto3" json:"tileId,omitempty"`
	EventTime            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=eventTime,proto3" json:"eventTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *TileInfo) Reset()         { *m = TileInfo{} }
func (m *TileInfo) String() string { return proto.CompactTextString(m) }
func (*TileInfo) ProtoMessage()    {}
func (*TileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{0}
}

func (m *TileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileInfo.Unmarshal(m, b)
}
func (m *TileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileInfo.Marshal(b, m, deterministic)
}
func (m *TileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileInfo.Merge(m, src)
}
func (m *TileInfo) XXX_Size() int {
	return xxx_messageInfo_TileInfo.Size(m)
}
func (m *TileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TileInfo proto.InternalMessageInfo

func (m *TileInfo) GetTvEmac() string {
	if m != nil {
		return m.TvEmac
	}
	return ""
}

func (m *TileInfo) GetTileId() string {
	if m != nil {
		return m.TileId
	}
	return ""
}

func (m *TileInfo) GetEventTime() *timestamp.Timestamp {
	if m != nil {
		return m.EventTime
	}
	return nil
}

type TileClickResponse struct {
	IsRegistered         bool     `protobuf:"varint,1,opt,name=isRegistered,proto3" json:"isRegistered,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *TileClickResponse) Reset()         { *m = TileClickResponse{} }
func (m *TileClickResponse) String() string { return proto.CompactTextString(m) }
func (*TileClickResponse) ProtoMessage()    {}
func (*TileClickResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{1}
}

func (m *TileClickResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileClickResponse.Unmarshal(m, b)
}
func (m *TileClickResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileClickResponse.Marshal(b, m, deterministic)
}
func (m *TileClickResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileClickResponse.Merge(m, src)
}
func (m *TileClickResponse) XXX_Size() int {
	return xxx_messageInfo_TileClickResponse.Size(m)
}
func (m *TileClickResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TileClickResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TileClickResponse proto.InternalMessageInfo

func (m *TileClickResponse) GetIsRegistered() bool {
	if m != nil {
		return m.IsRegistered
	}
	return false
}

type RemoveTvDeviceRequest struct {
	GoogleId             string   `protobuf:"bytes,1,opt,name=googleId,proto3" json:"googleId,omitempty"`
	TvEmac               string   `protobuf:"bytes,2,opt,name=tvEmac,proto3" json:"tvEmac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RemoveTvDeviceRequest) Reset()         { *m = RemoveTvDeviceRequest{} }
func (m *RemoveTvDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveTvDeviceRequest) ProtoMessage()    {}
func (*RemoveTvDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{2}
}

func (m *RemoveTvDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTvDeviceRequest.Unmarshal(m, b)
}
func (m *RemoveTvDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTvDeviceRequest.Marshal(b, m, deterministic)
}
func (m *RemoveTvDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTvDeviceRequest.Merge(m, src)
}
func (m *RemoveTvDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveTvDeviceRequest.Size(m)
}
func (m *RemoveTvDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTvDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTvDeviceRequest proto.InternalMessageInfo

func (m *RemoveTvDeviceRequest) GetGoogleId() string {
	if m != nil {
		return m.GoogleId
	}
	return ""
}

func (m *RemoveTvDeviceRequest) GetTvEmac() string {
	if m != nil {
		return m.TvEmac
	}
	return ""
}

type RemoveTvDeviceResponse struct {
	IsTvDeviceRemoved    bool     `protobuf:"varint,1,opt,name=isTvDeviceRemoved,proto3" json:"isTvDeviceRemoved,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RemoveTvDeviceResponse) Reset()         { *m = RemoveTvDeviceResponse{} }
func (m *RemoveTvDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveTvDeviceResponse) ProtoMessage()    {}
func (*RemoveTvDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{3}
}

func (m *RemoveTvDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTvDeviceResponse.Unmarshal(m, b)
}
func (m *RemoveTvDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTvDeviceResponse.Marshal(b, m, deterministic)
}
func (m *RemoveTvDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTvDeviceResponse.Merge(m, src)
}
func (m *RemoveTvDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveTvDeviceResponse.Size(m)
}
func (m *RemoveTvDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTvDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTvDeviceResponse proto.InternalMessageInfo

func (m *RemoveTvDeviceResponse) GetIsTvDeviceRemoved() bool {
	if m != nil {
		return m.IsTvDeviceRemoved
	}
	return false
}

type GetRequest struct {
	GoogleId             string   `protobuf:"bytes,1,opt,name=googleId,proto3" json:"googleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{4}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetGoogleId() string {
	if m != nil {
		return m.GoogleId
	}
	return ""
}

type DeleteRequest struct {
	GoogleId             string   `protobuf:"bytes,1,opt,name=googleId,proto3" json:"googleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{5}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetGoogleId() string {
	if m != nil {
		return m.GoogleId
	}
	return ""
}

type DeleteReponse struct {
	IsDeleted            bool     `protobuf:"varint,1,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DeleteReponse) Reset()         { *m = DeleteReponse{} }
func (m *DeleteReponse) String() string { return proto.CompactTextString(m) }
func (*DeleteReponse) ProtoMessage()    {}
func (*DeleteReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{6}
}

func (m *DeleteReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReponse.Unmarshal(m, b)
}
func (m *DeleteReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReponse.Marshal(b, m, deterministic)
}
func (m *DeleteReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReponse.Merge(m, src)
}
func (m *DeleteReponse) XXX_Size() int {
	return xxx_messageInfo_DeleteReponse.Size(m)
}
func (m *DeleteReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReponse proto.InternalMessageInfo

func (m *DeleteReponse) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

type LinkedDeviceResponse struct {
	IsLinkedDeviceFetched bool            `protobuf:"varint,1,opt,name=isLinkedDeviceFetched,proto3" json:"isLinkedDeviceFetched,omitempty"`
	LinkedDevices         []*LinkedDevice `protobuf:"bytes,2,rep,name=linkedDevices,proto3" json:"linkedDevices,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}        `json:"-" bson:"-"`
	XXX_unrecognized      []byte          `json:"-" bson:"-"`
	XXX_sizecache         int32           `json:"-" bson:"-"`
}

func (m *LinkedDeviceResponse) Reset()         { *m = LinkedDeviceResponse{} }
func (m *LinkedDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*LinkedDeviceResponse) ProtoMessage()    {}
func (*LinkedDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{7}
}

func (m *LinkedDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkedDeviceResponse.Unmarshal(m, b)
}
func (m *LinkedDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkedDeviceResponse.Marshal(b, m, deterministic)
}
func (m *LinkedDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkedDeviceResponse.Merge(m, src)
}
func (m *LinkedDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_LinkedDeviceResponse.Size(m)
}
func (m *LinkedDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkedDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LinkedDeviceResponse proto.InternalMessageInfo

func (m *LinkedDeviceResponse) GetIsLinkedDeviceFetched() bool {
	if m != nil {
		return m.IsLinkedDeviceFetched
	}
	return false
}

func (m *LinkedDeviceResponse) GetLinkedDevices() []*LinkedDevice {
	if m != nil {
		return m.LinkedDevices
	}
	return nil
}

type TvDevice struct {
	GoogleId             string        `protobuf:"bytes,1,opt,name=googleId,proto3" json:"googleId,omitempty"`
	LinkedDevice         *LinkedDevice `protobuf:"bytes,2,opt,name=linkedDevice,proto3" json:"linkedDevice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-" bson:"-"`
	XXX_unrecognized     []byte        `json:"-" bson:"-"`
	XXX_sizecache        int32         `json:"-" bson:"-"`
}

func (m *TvDevice) Reset()         { *m = TvDevice{} }
func (m *TvDevice) String() string { return proto.CompactTextString(m) }
func (*TvDevice) ProtoMessage()    {}
func (*TvDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{8}
}

func (m *TvDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TvDevice.Unmarshal(m, b)
}
func (m *TvDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TvDevice.Marshal(b, m, deterministic)
}
func (m *TvDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TvDevice.Merge(m, src)
}
func (m *TvDevice) XXX_Size() int {
	return xxx_messageInfo_TvDevice.Size(m)
}
func (m *TvDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_TvDevice.DiscardUnknown(m)
}

var xxx_messageInfo_TvDevice proto.InternalMessageInfo

func (m *TvDevice) GetGoogleId() string {
	if m != nil {
		return m.GoogleId
	}
	return ""
}

func (m *TvDevice) GetLinkedDevice() *LinkedDevice {
	if m != nil {
		return m.LinkedDevice
	}
	return nil
}

type UpdateResponse struct {
	IsUpdated            bool     `protobuf:"varint,1,opt,name=isUpdated,proto3" json:"isUpdated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{9}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetIsUpdated() bool {
	if m != nil {
		return m.IsUpdated
	}
	return false
}

type CreateReponse struct {
	IsCreated            bool     `protobuf:"varint,1,opt,name=isCreated,proto3" json:"isCreated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *CreateReponse) Reset()         { *m = CreateReponse{} }
func (m *CreateReponse) String() string { return proto.CompactTextString(m) }
func (*CreateReponse) ProtoMessage()    {}
func (*CreateReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{10}
}

func (m *CreateReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReponse.Unmarshal(m, b)
}
func (m *CreateReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReponse.Marshal(b, m, deterministic)
}
func (m *CreateReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReponse.Merge(m, src)
}
func (m *CreateReponse) XXX_Size() int {
	return xxx_messageInfo_CreateReponse.Size(m)
}
func (m *CreateReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReponse proto.InternalMessageInfo

func (m *CreateReponse) GetIsCreated() bool {
	if m != nil {
		return m.IsCreated
	}
	return false
}

type User struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	GoogleId             string               `protobuf:"bytes,4,opt,name=googleId,proto3" json:"googleId,omitempty"`
	Genre                []string             `protobuf:"bytes,5,rep,name=genre,proto3" json:"genre,omitempty"`
	Language             []string             `protobuf:"bytes,6,rep,name=language,proto3" json:"language,omitempty"`
	ContentType          []string             `protobuf:"bytes,7,rep,name=contentType,proto3" json:"contentType,omitempty"`
	LinkedDevices        []*LinkedDevice      `protobuf:"bytes,8,rep,name=linkedDevices,proto3" json:"linkedDevices,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{11}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetGoogleId() string {
	if m != nil {
		return m.GoogleId
	}
	return ""
}

func (m *User) GetGenre() []string {
	if m != nil {
		return m.Genre
	}
	return nil
}

func (m *User) GetLanguage() []string {
	if m != nil {
		return m.Language
	}
	return nil
}

func (m *User) GetContentType() []string {
	if m != nil {
		return m.ContentType
	}
	return nil
}

func (m *User) GetLinkedDevices() []*LinkedDevice {
	if m != nil {
		return m.LinkedDevices
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type LinkedDevice struct {
	TvEmac               string   `protobuf:"bytes,1,opt,name=tvEmac,proto3" json:"tvEmac,omitempty"`
	TvPanel              string   `protobuf:"bytes,2,opt,name=tvPanel,proto3" json:"tvPanel,omitempty"`
	TvBoard              string   `protobuf:"bytes,3,opt,name=tvBoard,proto3" json:"tvBoard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *LinkedDevice) Reset()         { *m = LinkedDevice{} }
func (m *LinkedDevice) String() string { return proto.CompactTextString(m) }
func (*LinkedDevice) ProtoMessage()    {}
func (*LinkedDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{12}
}

func (m *LinkedDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkedDevice.Unmarshal(m, b)
}
func (m *LinkedDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkedDevice.Marshal(b, m, deterministic)
}
func (m *LinkedDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkedDevice.Merge(m, src)
}
func (m *LinkedDevice) XXX_Size() int {
	return xxx_messageInfo_LinkedDevice.Size(m)
}
func (m *LinkedDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkedDevice.DiscardUnknown(m)
}

var xxx_messageInfo_LinkedDevice proto.InternalMessageInfo

func (m *LinkedDevice) GetTvEmac() string {
	if m != nil {
		return m.TvEmac
	}
	return ""
}

func (m *LinkedDevice) GetTvPanel() string {
	if m != nil {
		return m.TvPanel
	}
	return ""
}

func (m *LinkedDevice) GetTvBoard() string {
	if m != nil {
		return m.TvBoard
	}
	return ""
}

func init() {
	proto.RegisterType((*TileInfo)(nil), "UserService.TileInfo")
	proto.RegisterType((*TileClickResponse)(nil), "UserService.TileClickResponse")
	proto.RegisterType((*RemoveTvDeviceRequest)(nil), "UserService.RemoveTvDeviceRequest")
	proto.RegisterType((*RemoveTvDeviceResponse)(nil), "UserService.RemoveTvDeviceResponse")
	proto.RegisterType((*GetRequest)(nil), "UserService.GetRequest")
	proto.RegisterType((*DeleteRequest)(nil), "UserService.DeleteRequest")
	proto.RegisterType((*DeleteReponse)(nil), "UserService.DeleteReponse")
	proto.RegisterType((*LinkedDeviceResponse)(nil), "UserService.LinkedDeviceResponse")
	proto.RegisterType((*TvDevice)(nil), "UserService.TvDevice")
	proto.RegisterType((*UpdateResponse)(nil), "UserService.UpdateResponse")
	proto.RegisterType((*CreateReponse)(nil), "UserService.CreateReponse")
	proto.RegisterType((*User)(nil), "UserService.User")
	proto.RegisterType((*LinkedDevice)(nil), "UserService.LinkedDevice")
}

func init() { proto.RegisterFile("UserService.proto", fileDescriptor_e7864342a5dd7108) }

var fileDescriptor_e7864342a5dd7108 = []byte{
	// 799 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x56, 0xd2, 0x34, 0x4d, 0x26, 0xfd, 0x8a, 0xdf, 0x24, 0xaf, 0x31, 0x15, 0x84, 0xe5, 0x12,
	0x15, 0x48, 0xa4, 0x82, 0x04, 0xaa, 0x84, 0x50, 0x69, 0x69, 0x55, 0xa8, 0x10, 0x4a, 0xd3, 0x0b,
	0x1f, 0x07, 0xd7, 0x9e, 0xa6, 0xab, 0xfa, 0x23, 0x78, 0x37, 0x91, 0xb8, 0x72, 0xe7, 0xc4, 0x4f,
	0xe3, 0x2f, 0x70, 0xe3, 0x07, 0x70, 0x45, 0xbb, 0x6b, 0x27, 0xbb, 0x49, 0xd3, 0x16, 0x6e, 0x9e,
	0x67, 0x66, 0x9f, 0x99, 0x79, 0x66, 0x76, 0x0d, 0xd5, 0x13, 0x86, 0xc9, 0x31, 0x26, 0x23, 0xea,
	0x61, 0x7b, 0x90, 0xc4, 0x3c, 0xb6, 0x2a, 0x1a, 0xe4, 0xdc, 0xed, 0xc7, 0x71, 0x3f, 0xc0, 0x8e,
	0x74, 0x9d, 0x0e, 0xcf, 0x3a, 0x9c, 0x86, 0xc8, 0xb8, 0x1b, 0x0e, 0x54, 0xb4, 0xb3, 0x91, 0x06,
	0xb8, 0x03, 0xda, 0x71, 0xa3, 0x28, 0xe6, 0x2e, 0xa7, 0x71, 0xc4, 0x94, 0x97, 0x70, 0x28, 0xf5,
	0x68, 0x80, 0x87, 0xd1, 0x59, 0x6c, 0x35, 0xa0, 0xc8, 0x47, 0xaf, 0x42, 0xd7, 0xb3, 0x73, 0xcd,
	0x5c, 0xab, 0xdc, 0x4d, 0x2d, 0x89, 0x8b, 0x18, 0xdf, 0xce, 0xa7, 0xb8, 0xb4, 0xac, 0x67, 0x50,
	0xc6, 0x11, 0x46, 0xbc, 0x47, 0x43, 0xb4, 0x0b, 0xcd, 0x5c, 0xab, 0xb2, 0xe5, 0xb4, 0x55, 0xb6,
	0x76, 0x56, 0x4e, 0xbb, 0x97, 0x95, 0xd3, 0x9d, 0x04, 0x93, 0xa7, 0x50, 0x15, 0x59, 0x77, 0x03,
	0xea, 0x5d, 0x74, 0x91, 0x0d, 0xe2, 0x88, 0xa1, 0x45, 0x60, 0x99, 0xb2, 0x2e, 0xf6, 0x29, 0xe3,
	0x98, 0xa0, 0x2f, 0x8b, 0x28, 0x75, 0x0d, 0x8c, 0xbc, 0x81, 0x7a, 0x17, 0xc3, 0x78, 0x84, 0xbd,
	0xd1, 0x1e, 0x8a, 0xfe, 0xbb, 0xf8, 0x79, 0x88, 0x8c, 0x5b, 0x0e, 0x94, 0x54, 0xe6, 0x43, 0x3f,
	0xad, 0x7e, 0x6c, 0x6b, 0x7d, 0xe5, 0xf5, 0xbe, 0xc8, 0x3e, 0x34, 0xa6, 0xc9, 0xd2, 0x52, 0x1e,
	0x42, 0x95, 0xb2, 0x09, 0x2a, 0x62, 0xb2, 0x7a, 0x66, 0x1d, 0xa4, 0x05, 0x70, 0x80, 0xfc, 0x06,
	0x95, 0x90, 0x07, 0xb0, 0xb2, 0x87, 0x01, 0xf2, 0x9b, 0x94, 0x4d, 0x1e, 0x4d, 0x82, 0x55, 0x55,
	0x1b, 0x50, 0xa6, 0x4c, 0x41, 0x59, 0x35, 0x13, 0x80, 0x7c, 0xcb, 0x41, 0xed, 0x88, 0x46, 0x17,
	0xe8, 0x4f, 0x35, 0xf3, 0x04, 0xea, 0x94, 0xe9, 0x9e, 0x7d, 0xe4, 0xde, 0xf9, 0x98, 0xe2, 0x72,
	0xa7, 0xf5, 0x02, 0x56, 0x02, 0x0d, 0x66, 0x76, 0xbe, 0xb9, 0xd0, 0xaa, 0x6c, 0xdd, 0x6a, 0xeb,
	0xfb, 0x68, 0xe4, 0x33, 0xe3, 0x09, 0x42, 0x29, 0x13, 0xea, 0xca, 0xe9, 0x3c, 0x87, 0x65, 0xfd,
	0xa0, 0x9c, 0xd1, 0x95, 0x79, 0x8c, 0x70, 0xd2, 0x86, 0xd5, 0x93, 0x81, 0xef, 0xf2, 0x49, 0xbf,
	0x52, 0x26, 0x85, 0x69, 0x32, 0xa5, 0x80, 0x50, 0x75, 0x37, 0x41, 0x77, 0x4a, 0x55, 0x05, 0x69,
	0xe1, 0x29, 0x40, 0x7e, 0xe7, 0xa1, 0x20, 0x2a, 0xb1, 0x2c, 0x28, 0x44, 0x6e, 0x88, 0x69, 0xf9,
	0xf2, 0xdb, 0xaa, 0xc1, 0x22, 0x86, 0x2e, 0x0d, 0xd2, 0xbd, 0x52, 0x86, 0xd5, 0x84, 0xca, 0xe0,
	0x3c, 0x8e, 0xf0, 0xed, 0x30, 0x3c, 0xc5, 0xc4, 0x5e, 0x90, 0x3e, 0x1d, 0x32, 0xe4, 0x28, 0x4c,
	0xc9, 0x51, 0x83, 0xc5, 0x3e, 0x46, 0x09, 0xda, 0x8b, 0xcd, 0x05, 0xc1, 0x29, 0x0d, 0x71, 0x22,
	0x70, 0xa3, 0xfe, 0xd0, 0xed, 0xa3, 0x5d, 0x94, 0x8e, 0xb1, 0x2d, 0xf2, 0x79, 0x71, 0xc4, 0xc5,
	0xdd, 0xfa, 0x32, 0x40, 0x7b, 0x49, 0xba, 0x75, 0x68, 0x76, 0x96, 0xa5, 0xbf, 0x9b, 0xa5, 0xb8,
	0xe9, 0x9e, 0x12, 0x64, 0x87, 0xdb, 0xe5, 0xeb, 0x6f, 0xfa, 0x38, 0x58, 0x9c, 0x1c, 0x2a, 0xe5,
	0x77, 0xb8, 0x0d, 0xd7, 0x9f, 0x1c, 0x07, 0x93, 0xf7, 0xb0, 0xac, 0x97, 0x34, 0xf7, 0x75, 0xb2,
	0x61, 0x89, 0x8f, 0xde, 0xb9, 0x11, 0x66, 0x63, 0xc8, 0x4c, 0xe5, 0x79, 0x19, 0xbb, 0x89, 0x9f,
	0x0e, 0x21, 0x33, 0xb7, 0x7e, 0x15, 0x41, 0x7f, 0x44, 0xad, 0x63, 0x00, 0x35, 0x70, 0x39, 0xea,
	0xaa, 0xa1, 0x8b, 0xf8, 0x76, 0x1c, 0x03, 0x32, 0x16, 0x88, 0x34, 0xbe, 0xfe, 0xf8, 0xf9, 0x3d,
	0xbf, 0x4e, 0x2a, 0x1d, 0xd5, 0xf6, 0x90, 0x61, 0xb2, 0x9d, 0xdb, 0xb4, 0x7a, 0x00, 0x6a, 0xe9,
	0xe6, 0x91, 0xde, 0x36, 0x21, 0x63, 0x8b, 0x35, 0x56, 0x25, 0x49, 0xc6, 0xfa, 0x11, 0x40, 0xdd,
	0x78, 0xc9, 0x6a, 0xd6, 0x65, 0xbc, 0x2d, 0xce, 0xe5, 0xbe, 0x69, 0x76, 0x5f, 0xe2, 0x19, 0xfb,
	0x6b, 0x58, 0x3a, 0x40, 0x2e, 0xa9, 0xff, 0x37, 0x8e, 0x4f, 0x1e, 0x38, 0x67, 0xb6, 0x13, 0xf2,
	0x9f, 0xa4, 0x5b, 0x21, 0xa5, 0x4e, 0x1f, 0x79, 0xc6, 0x75, 0x06, 0xab, 0x6a, 0x80, 0xe3, 0x67,
	0xa0, 0x6e, 0x9c, 0xcc, 0x60, 0xe7, 0xde, 0xfc, 0x3d, 0xcc, 0xd4, 0x70, 0x64, 0x82, 0x1a, 0x59,
	0xeb, 0xa8, 0xc5, 0xe4, 0x23, 0x5f, 0x06, 0x88, 0x3c, 0x43, 0x58, 0x35, 0x9f, 0x71, 0x8b, 0x18,
	0x84, 0x97, 0xfe, 0x30, 0x9c, 0xfb, 0x57, 0xc6, 0xcc, 0xa4, 0x4d, 0x64, 0x80, 0x9e, 0x36, 0x80,
	0xf5, 0x03, 0xe4, 0x47, 0xc6, 0x3d, 0x99, 0xab, 0xd9, 0x0d, 0x5a, 0xdc, 0x90, 0xb9, 0x1a, 0xa4,
	0x2a, 0x34, 0x54, 0x5d, 0xaa, 0x64, 0x4c, 0x64, 0xfb, 0x00, 0xe5, 0xf1, 0x1f, 0x73, 0x5a, 0xc7,
	0xf4, 0xff, 0xed, 0xdc, 0x99, 0x81, 0x8d, 0x1f, 0x2c, 0xa9, 0xcb, 0x0c, 0x6b, 0x04, 0x3a, 0xe2,
	0x07, 0xee, 0x09, 0xdf, 0x76, 0x6e, 0xb3, 0x95, 0xb3, 0x3e, 0x01, 0x88, 0xe8, 0x63, 0x0c, 0xd0,
	0xe3, 0xff, 0xca, 0x3e, 0x59, 0x29, 0xc1, 0xce, 0x24, 0x97, 0xa4, 0x3f, 0x2d, 0xca, 0x8b, 0xfe,
	0xf8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x4f, 0x24, 0x32, 0xcb, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*CreateReponse, error)
	UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*UpdateResponse, error)
	DeleteUser(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReponse, error)
	GetUser(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*User, error)
	LinkedTvDevice(ctx context.Context, in *TvDevice, opts ...grpc.CallOption) (*LinkedDeviceResponse, error)
	RemoveTvDevice(ctx context.Context, in *RemoveTvDeviceRequest, opts ...grpc.CallOption) (*RemoveTvDeviceResponse, error)
	GetLinkedDevices(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*LinkedDeviceResponse, error)
	TileClick(ctx context.Context, opts ...grpc.CallOption) (UserService_TileClickClient, error)
	TileSelect(ctx context.Context, opts ...grpc.CallOption) (UserService_TileSelectClient, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*CreateReponse, error) {
	out := new(CreateReponse)
	err := c.cc.Invoke(ctx, "/UserService.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/UserService.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReponse, error) {
	out := new(DeleteReponse)
	err := c.cc.Invoke(ctx, "/UserService.UserService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/UserService.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LinkedTvDevice(ctx context.Context, in *TvDevice, opts ...grpc.CallOption) (*LinkedDeviceResponse, error) {
	out := new(LinkedDeviceResponse)
	err := c.cc.Invoke(ctx, "/UserService.UserService/LinkedTvDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RemoveTvDevice(ctx context.Context, in *RemoveTvDeviceRequest, opts ...grpc.CallOption) (*RemoveTvDeviceResponse, error) {
	out := new(RemoveTvDeviceResponse)
	err := c.cc.Invoke(ctx, "/UserService.UserService/RemoveTvDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetLinkedDevices(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*LinkedDeviceResponse, error) {
	out := new(LinkedDeviceResponse)
	err := c.cc.Invoke(ctx, "/UserService.UserService/GetLinkedDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) TileClick(ctx context.Context, opts ...grpc.CallOption) (UserService_TileClickClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UserService_serviceDesc.Streams[0], "/UserService.UserService/TileClick", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceTileClickClient{stream}
	return x, nil
}

type UserService_TileClickClient interface {
	Send(*TileInfo) error
	CloseAndRecv() (*TileClickResponse, error)
	grpc.ClientStream
}

type userServiceTileClickClient struct {
	grpc.ClientStream
}

func (x *userServiceTileClickClient) Send(m *TileInfo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userServiceTileClickClient) CloseAndRecv() (*TileClickResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(TileClickResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) TileSelect(ctx context.Context, opts ...grpc.CallOption) (UserService_TileSelectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UserService_serviceDesc.Streams[1], "/UserService.UserService/TileSelect", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceTileSelectClient{stream}
	return x, nil
}

type UserService_TileSelectClient interface {
	Send(*TileInfo) error
	CloseAndRecv() (*TileClickResponse, error)
	grpc.ClientStream
}

type userServiceTileSelectClient struct {
	grpc.ClientStream
}

func (x *userServiceTileSelectClient) Send(m *TileInfo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userServiceTileSelectClient) CloseAndRecv() (*TileClickResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(TileClickResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *User) (*CreateReponse, error)
	UpdateUser(context.Context, *User) (*UpdateResponse, error)
	DeleteUser(context.Context, *DeleteRequest) (*DeleteReponse, error)
	GetUser(context.Context, *GetRequest) (*User, error)
	LinkedTvDevice(context.Context, *TvDevice) (*LinkedDeviceResponse, error)
	RemoveTvDevice(context.Context, *RemoveTvDeviceRequest) (*RemoveTvDeviceResponse, error)
	GetLinkedDevices(context.Context, *GetRequest) (*LinkedDeviceResponse, error)
	TileClick(UserService_TileClickServer) error
	TileSelect(UserService_TileSelectServer) error
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *User) (*CreateReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUser(ctx context.Context, req *User) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServiceServer) DeleteUser(ctx context.Context, req *DeleteRequest) (*DeleteReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedUserServiceServer) GetUser(ctx context.Context, req *GetRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserServiceServer) LinkedTvDevice(ctx context.Context, req *TvDevice) (*LinkedDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkedTvDevice not implemented")
}
func (*UnimplementedUserServiceServer) RemoveTvDevice(ctx context.Context, req *RemoveTvDeviceRequest) (*RemoveTvDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTvDevice not implemented")
}
func (*UnimplementedUserServiceServer) GetLinkedDevices(ctx context.Context, req *GetRequest) (*LinkedDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLinkedDevices not implemented")
}
func (*UnimplementedUserServiceServer) TileClick(srv UserService_TileClickServer) error {
	return status.Errorf(codes.Unimplemented, "method TileClick not implemented")
}
func (*UnimplementedUserServiceServer) TileSelect(srv UserService_TileSelectServer) error {
	return status.Errorf(codes.Unimplemented, "method TileSelect not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LinkedTvDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TvDevice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LinkedTvDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService.UserService/LinkedTvDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LinkedTvDevice(ctx, req.(*TvDevice))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RemoveTvDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTvDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RemoveTvDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService.UserService/RemoveTvDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RemoveTvDevice(ctx, req.(*RemoveTvDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetLinkedDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetLinkedDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService.UserService/GetLinkedDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetLinkedDevices(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_TileClick_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserServiceServer).TileClick(&userServiceTileClickServer{stream})
}

type UserService_TileClickServer interface {
	SendAndClose(*TileClickResponse) error
	Recv() (*TileInfo, error)
	grpc.ServerStream
}

type userServiceTileClickServer struct {
	grpc.ServerStream
}

func (x *userServiceTileClickServer) SendAndClose(m *TileClickResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userServiceTileClickServer) Recv() (*TileInfo, error) {
	m := new(TileInfo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _UserService_TileSelect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserServiceServer).TileSelect(&userServiceTileSelectServer{stream})
}

type UserService_TileSelectServer interface {
	SendAndClose(*TileClickResponse) error
	Recv() (*TileInfo, error)
	grpc.ServerStream
}

type userServiceTileSelectServer struct {
	grpc.ServerStream
}

func (x *userServiceTileSelectServer) SendAndClose(m *TileClickResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userServiceTileSelectServer) Recv() (*TileInfo, error) {
	m := new(TileInfo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserService.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "LinkedTvDevice",
			Handler:    _UserService_LinkedTvDevice_Handler,
		},
		{
			MethodName: "RemoveTvDevice",
			Handler:    _UserService_RemoveTvDevice_Handler,
		},
		{
			MethodName: "GetLinkedDevices",
			Handler:    _UserService_GetLinkedDevices_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TileClick",
			Handler:       _UserService_TileClick_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "TileSelect",
			Handler:       _UserService_TileSelect_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "UserService.proto",
}
